language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: l26u6hsD6eJ/IkoqATBtJCHZPbcSDwxazID/vE26zJ6upNm+pNfi+AVhmiK39LWTayncYD3jjU2lO1VUyGocxTmvsJq3IIJ5NWQOoNx2NE6Q92/6Y0J+qhYcmt8Puk5rIABH60RdQt4A0Zo+Xd9WkpSau/zpshgNWzPgwBm0aZg=
  - secure: aLHAC0txu6lBq2VPJIlXfw4GyShXysdr5CrH83WJbpEmXH5QOEyECXu5+pPLgbYAF+zeP2ewdNlg/FEHNO/RnhcDVjvuNoTnQ+ap4dwRNMb1/sCYo9IcNw6Hx8lMHykzpwyZ26gaovEzGWdxxql8D0B2WKfzdVs+sZ3qEqJRDKg=
  - secure: fAs++a4rj8BvJ9rWuVF74+T58NeAcnyJa3glCbeLUA+VgY4qGQ9dLBICv9inB7M6i17CeCtUCcykkOZClTCOSgBdCQL2htChJ/9L2U7NjIpIZi/a+pqCO8GAB3/lOdS5TsKvJOuJ7cs6d9pJDVGwwlcRakixT8Ah8BeEfethL1k=
